Qrcode feature
winsby/colorful-sats pull request #6
Opened 2023-08-07 20:17 UTC by hwinsby

Created basic function for QR code invoicing.
GetAlby function paused for now. 
Refactored code for imagine, variation, and upscale calls.
Styles for QR invoicing are still wip.

2023-08-09 23:51 UTC, winsby requested changes
Great work! Much nicer now. Mostly just small nits and cleanup requested.

2023-08-09 23:51 UTC, winsby commented on client/src/components/ImageGenerator/ImageGenerator.jsx
> +import { processWebExtentionPayment } from "../../utils/lightningUtils";
```suggestion
import { SlideOut } from "../general/SlideOut";
import { processWebExtentionPayment } from "../../utils/lightningUtils";

import styles from "./ImageGenerator.module.scss";
```

2023-08-09 23:51 UTC, winsby commented on client/src/components/ImageGenerator/ImageGenerator.jsx
> +  const onClickUpscale = () => {
```suggestion
  const handleClickUpscale = () => {
```

2023-08-09 23:51 UTC, winsby commented on client/src/components/ImageGenerator/ImageGenerator.jsx
> +  // Determins which top card to display
```suggestion
  // Determines which top card to display
```

2023-08-09 23:51 UTC, winsby commented on client/src/components/ImageGenerator/functions.ts
> +import { processPayment } from "../../utils/lightningUtils.js";
You should delete the extra lightingUtils.ts file and change this line.

```suggestion
import { processPayment } from "../../utils/lightningUtils";
```

2023-08-09 23:51 UTC, winsby commented on client/src/components/ImageGenerator/functions.ts
> +};
Doesn't look like this function is used anywhere anymore.

```suggestion
```

2023-08-09 23:51 UTC, winsby commented on client/src/components/PaymentModal/InvoiceExpirationTimer.jsx
> +          <div>Invoice has Expired</div>
```suggestion
          <div>Invoice has expired</div>
```

2023-08-09 23:51 UTC, winsby commented on client/src/components/ImageGenerator/ImageGenerator.jsx
> +  const [modalType, setModalType] = useState("defaultModal");
This is just a note to look back on when you eventually convert to typescript. These strings for the different modal types would a great place to use a typescript string enum.

```typescript
enum ModalTypeEnum {
   defaultModal: "defaultModal",
   successModal: "successModal",
}
```

You could then access the enum properties with something like `ModalTypeEnum.defaultModal`, which equates to `"defaultModal"`.

2023-08-09 23:51 UTC, winsby commented on client/src/components/PaymentModal/PaymentModal.jsx
> +        )}
This is overall fine for now since you just have the two types of modals, but a function with more ifs or a switch statement to handle which is displayed would be more flexible for the future.

2023-08-09 23:51 UTC, winsby commented on client/src/components/PrimaryInputs/functions.js
Take a look at this file. Github says it's empty. If that's true, you should delete it.

2023-08-09 23:51 UTC, winsby commented on client/src/utils/lightningUtils.ts
Delete this file.

2023-08-10 02:28 UTC, hwinsby commented on client/src/components/ImageGenerator/ImageGenerator.jsx
> +  const [modalType, setModalType] = useState("defaultModal");
Interesting. I'll need to keep working on my codecademy course so I'll understand more.

2023-08-10 02:29 UTC, hwinsby commented on client/src/components/PaymentModal/PaymentModal.jsx
> +        )}
Yes, I actually had a switch statement written at first when I thought there were going to be more iterations. I deleted that function because this made more sense to me with just two.

2023-08-10 02:49 UTC, hwinsby commented
Went over your notes and made the requested changes plus one extra unused file deleted and one styles file changed slightly. Lmk what else you need. Thanks!

2023-08-10 03:07 UTC, winsby approved these changes
🔥

2023-08-10 03:07 UTC, merged